<a href="https://colab.research.google.com/github/manhhung20033/manhhung20033/blob/main/Learn_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hello world


In [ ]:
#this is a comment
print("Hello world")
print(5/8)
5/8 # this only prints in IPython notebooks and shells.

Hello world
0.625


0.625

Basic data types

Python has all the basic data types and operation: int, float, str, bool, None.

In [ ]:
#You can use type() to get a variable's type
s = 5
type(s)
s > 3 #using Booleans: True or False 
s = "The answer is "
type(s)

str

In [ ]:
1.0 + 2       # float + int -> float
s + str(42)   # string + string
# s + 42      # bad: string + int 

'The answer is 42'

Complex types

The main complex data types are list, tuples, sets and dictionaries (dicts).

In [ ]:
l = [1,2,3,4,5,6,6]     # list
t = (1,2,3,4,5,6)       # tuple: like a list, but immutable
s =set((1,2,3,4,5,6))   # set: unordered, you need to use add() to add new elemen
d = {2: "a",            # dict: has key - value pairs
    3: "b",
    "foo": "c",
    "bar": "d"}

l #Note how each of these is printed
t
s
d

{2: 'a', 3: 'b', 'foo': 'c', 'bar': 'd'}

You can use indices to retrun a value (except for sets, they are unordered)

In [ ]:
l
l[2]
t
t[2]
d
d["bar"]

'd'

In [ ]:
l
l[2] = 7 #Lists are mutable
l

[1, 2, 7, 4, 5, 6, 6]

Python allows convenient tuple packing/unpacking

In [ ]:
b = ("Bob", 19, "CS")       # tuple packing
(name,age,studies) = b      #tuple unpacking
name,age

('Bob', 19)

**STRING**

In [ ]:
s = "the %s is %d" % ('answer', 42)
s   # %s -> answer; %d -> 42
s[0]
s[4:10]

'answer'

The also have a format() function for more complex formatting

In [ ]:
l = [1,2,3,4,5,6]
"{}".format(l)
"%s" % l
"{first} {last}".format(**{'first':'Hodor',
                           'last' : 'Hodor!'})

'Hodor Hodor!'

**FOR LOOPS, IF STATEMENTS**

In [ ]:
l = [1,2,3]
d = {"foo" : "c", "bar" : "d"}

for i in l:
    print(i)

for k,v in d.items() : #Note how key-value pairs are extracted
    print ("%s : %s" % (k,v))

if len(l) > 3:
    print('Long list')
else:
    print ('Short list')


1
2
3
foo : c
bar : d
Short list


**FUNCTION**

In [ ]:
def myfunc(a,b):
    return a +b

myfunc(2,3)

5

Function arguments (parameters) can be:
  - Variable-length (indicated with *)
  - a dictionary of keyword arguments (indicated with **)
  - Given a default value, in which case they are not required (but have to come last) 

In [ ]:
def func(*argv, **kwarg):
  print("func argv: %s" % str(argv) )
  print("func lwarg: %s" % str(kwarg))

func(2,3,a=4)

def func (a):
  print(a*a)

func(3)

func argv: (2, 3)
func lwarg: {'a': 4}
9


In [ ]:
def fund(*argv):
  return sum(argv[0:2], sum(argv[2:4]))

fund(2,6)

8

In [ ]:
def squares(limit):
    r = 0
    ret = []
    while r < limit:
      ret.append(r**2)
      r +=1
    return ret

for i in squares(4):
  print(i)

0
1
4
9


Functions can be passed as arguments to other functions

In [ ]:
def greet(name):
    return "hello " + name

name = "hung"
greet(name)


'hello hung'

In [ ]:
def call_func(func):
  other_name = "john"
  return func(other_name)
call_func(greet)

'hello john'

In [ ]:
def compose_greet_func():
  def get_message():
    return "hello there!"
  return get_message

greet = compose_greet_func()
greet()

'hello there!'

**CLASSES**

defined

In [ ]:
class TestClass(object): # TestClass inherits from object.
    myvar = ""

    def __init__(self, myString): # optional constructor, returns nothing
        self.myvar = myString # 'self' is used to store instance properties
    
    def say(self, what): # you need to add self as the first argument 
        return self.myvar + str(what)

a = TestClass("The new answer is ")
#a.myvar # You can retrieve all properties of self
a.say(42)

'The new answer is 42'

use static function

In [ ]:
class TestClass(object):
    myvar = ""
    
    def __init__(self, myString): 
        self.myvar = myString
    
    def say(self, what): # you need to add self as the first argument 
        return self.myvar + str(what)
    
    @staticmethod
    def sayStatic(what): # or declare the function static 
        return "The answer is " + str(what)

a = TestClass("The new answer is ")
a.say(42)
a.sayStatic(42)

'The answer is 42'

**FUNCTIONAL PYTHON**

In [ ]:
def square(num):
    return num ** 2

# map(function, iterable) applies a given function to every element of a list
list(map(square, [1,2,3,4]))

list(map(lambda x: x**2, [1,2,3,4])) 
mydata = list(map(lambda x: x if x>2 else 0, [1,2,3,4])) 
mydata

# reduce(function, iterable ) applies a function with two arguments cumulatively to every element of a list
from functools import reduce
reduce(lambda x,y: x+y, [1,2,3,4]) 


10

In [ ]:
# filter(function, iterable)) extracts every element for which the function returns true
list(filter(lambda x: x>2, [1,2,3,4]))

[3, 4]

In [ ]:
# zip([iterable,...]) returns tuples of corresponding elements of multiple lists
list(zip([1,2,3,4],[5,6,7,8,9]))

[(1, 5), (2, 6), (3, 7), (4, 8)]

list comprehensions can create lists as follows:

[statement for var in iterable if condition]  

generators do the same, but are lazy: they don't create the list until it is needed:

(statement for var in list if condition)

In [ ]:
a = [2, 3, 4, 5]

lc = [ x for x in a if x >= 4 ] # List comprehension. Square brackets
lg = ( x for x in a if x >= 4 ) # Generator. Round brackets

a.extend([6,7,8,9])

for i in lc:
    print("%i " % i, end="") # end tells the print function not to end with a newline
print("\n")
for i in lg:
    print("%i " % i, end="")

4 5 

4 5 6 7 8 9 

list comprehensions
  {key:value for (key,value) in dict.items() if condition}  

In [ ]:
# Quick dictionary creation

numbers = range(10)
{n:n**2 for n in numbers if n%2 == 0}


{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}

 **PYTHON FOR SCIENTIFIC COMPUTING** 



Python has extentive packages to help with data analysis:

*   Numpy: matrices, linear algebra
*   scipy: advanced linear algebra and maths, signal processing, stactistics
*   pandas: DataFrames, data wraingling and analysis
*   malplotblib: Visualizations such as line charts, histograms, scatter plots

In [1]:
# General imports
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**NumPy**
Numpy is the fundamental package required for high performance scientific computing on python. It provides: 


*   ndarray: fast and space0efficient n-dimensionla numeric array with vectorized arthimetic operations
*   Functions for fast operations on arrays without having to write loops
*   Linear algebra, random number generation, Fourier transform
*   


**NDARRAY**

In [5]:
# Convert normal Python array to 1-dimensional numpy array
np.array((1, 2, 53))

array([ 1,  2, 53])

In [6]:
# Convert sequences of sequences of sequences ... to n-dim array
np.array([(1.5, 2, 3), (4, 5, 6)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
# Define element type at creation time
np.array([[1, 2], [3, 4]], dtype=complex)

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [8]:
my_array = np.array([[1, 0, 3], [0, 1, 2]])
my_array.ndim     # number of dimensions (axes), also called the rank
my_array.shape    # a matrix with n rows and m columns has shape (n,m)
my_array.size     # the total number of elements of the array
my_array.dtype    # type of the elements in the array
my_array.itemsize # the size in bytes of each element of the array

8

Create an array with placeholder than extending it later

In [9]:
np.ones(3) # Default type is float64
np.zeros([2, 2]) 
np.empty([2, 2]) # Fills the array with whatever sits in memory
np.random.random((2,3))
np.random.randint(5, size=(2, 4))

array([[3, 3, 0, 2],
       [0, 2, 2, 3]])

Create sequences of numbers

In [10]:
np.linspace(0, 1, num=6)   # Linearly distributed numbers between 0 and 1
np.arange(0, 1, step=0.3)  # Fixed step size
np.arange(12).reshape(3,4) # Create and reshape
np.eye(4)                  # Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
a, b    # Just printing
a-b
a > 32

array([False, False,  True,  True])

The matrix product can be performend using dot()

In [25]:
A, B = np.array([[1,1], [0,1]]), np.array([[2,0], [3,4]]) # assign multiple variables in one line
A
B
#A*B
np.dot(A,B)

array([[5, 4],
       [3, 4]])